# Generated by Django 3.0.6 on 2020-06-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='costo_utilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo_etecsa', models.FloatField(verbose_name='Costo Etecsa')),
                ('utilidad_diaria', models.FloatField(verbose_name='Utilidad Diaria')),
            ],
        ),
        migrations.CreateModel(
            name='rtv_cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cant', models.IntegerField(verbose_name='Cantidad')),
                ('valor_facial', models.FloatField(verbose_name='Valor Facial')),
                ('valor_etecsa', models.FloatField(verbose_name='Valor Etecsa')),
                ('ingreso_ag', models.FloatField(verbose_name='Ingreso A.G')),
            ],
        ),
        migrations.CreateModel(
            name='rtv_movil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cant', models.IntegerField(verbose_name='Cantidad')),
                ('valor_facial', models.FloatField(verbose_name='Valor Facial')),
                ('valor_etecsa', models.FloatField(verbose_name='Valor Etecsa')),
                ('ingreso_ag_cuc', models.FloatField(verbose_name='Ingreso A.G-CUC')),
                ('ingreso_ag_cup', models.FloatField(verbose_name='Ingreso A.G-CUP')),
            ],
        ),
        migrations.CreateModel(
            name='rtv_nauta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cant', models.IntegerField(verbose_name='Cantidad')),
                ('valor_facial', models.FloatField(verbose_name='Valor Facial')),
                ('valor_etecsa', models.FloatField(verbose_name='Valor Etecsa')),
                ('ingreso_ag_cuc', models.FloatField(verbose_name='Ingreso A.G-CUC')),
                ('ingreso_ag_cup', models.FloatField(verbose_name='Ingreso A.G-CUP')),
            ],
        ),
        migrations.CreateModel(
            name='trtv_cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tcant', models.IntegerField(verbose_name='Total: Cantidad')),
                ('tvalor_facial', models.FloatField(verbose_name='Total: Valor Facial')),
                ('tvalor_etecsa', models.FloatField(verbose_name='Total: Valor Etecsa')),
                ('tingreso_ag', models.FloatField(verbose_name='Total: Ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='trtv_movil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tcant', models.IntegerField(verbose_name='Total: Cantidad')),
                ('tvalor_facial', models.FloatField(verbose_name='Total: Valor Facial')),
                ('tvalor_etecsa', models.FloatField(verbose_name='Total: Valor Etecsa')),
                ('tingreso_ag_cuc', models.FloatField(verbose_name='Total: Ingreso A.G-CUC')),
                ('tingreso_ag_cup', models.FloatField(verbose_name='Total: Ingreso A.G-CUP')),
            ],
        ),
        migrations.CreateModel(
            name='trtv_nauta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tcant', models.IntegerField(verbose_name='Total: Cantidad')),
                ('tvalor_facial', models.FloatField(verbose_name='Total: Valor Facial')),
                ('tvalor_etecsa', models.FloatField(verbose_name='Total: Valor Etecsa')),
                ('tingreso_ag_cuc', models.FloatField(verbose_name='Total: Ingreso A.G-CUC')),
                ('tingreso_ag_cup', models.FloatField(verbose_name='Total: Ingreso A.G-CUP')),
            ],
        ),
    ]
